stack:
  name_cpp: RcppQueues::stack
  constructor:
    roxygen: |
      @export
  methods:
    pop:
      return_type: void
      access: function
      name_cpp: "RcppQueues::pop"
    push:
      args: [x: "int"]
      return_type: void
    equals:
      args: [other: "RcppQueues::stack"]
      name_cpp: RcppQueues::stack_eq
      access: function
      return_type: bool
    differs:
      args: [other: "RcppQueues::stack"]
      name_cpp: "operator!="
      access: function
      return_type: bool
  active:
    empty: {type: bool, access: member}
    size: {type: size_t, access: member}
    top: {type: int, access: function,
      name_cpp: "RcppQueues::top"}
