# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
parallelVectorSum <- function(x) {
    .Call('_RcppQueues_parallelVectorSum', PACKAGE = 'RcppQueues', x)
}

#' @export
parallelMatrixSqrt <- function(x) {
    .Call('_RcppQueues_parallelMatrixSqrt', PACKAGE = 'RcppQueues', x)
}

HumanEventQ__ctor <- function(initQ) {
    .Call('_RcppQueues_HumanEventQ__ctor', PACKAGE = 'RcppQueues', initQ)
}

HumanEventQ__firstEvent <- function(obj_) {
    .Call('_RcppQueues_HumanEventQ__firstEvent', PACKAGE = 'RcppQueues', obj_)
}

HumanEventQ__rmFirstEventFromQ <- function(obj_) {
    invisible(.Call('_RcppQueues_HumanEventQ__rmFirstEventFromQ', PACKAGE = 'RcppQueues', obj_))
}

HumanEventQ__rmTagFromQ <- function(obj_, tag) {
    invisible(.Call('_RcppQueues_HumanEventQ__rmTagFromQ', PACKAGE = 'RcppQueues', obj_, tag))
}

HumanEventQ__get_queueN <- function(obj_) {
    .Call('_RcppQueues_HumanEventQ__get_queueN', PACKAGE = 'RcppQueues', obj_)
}

HumanEventQ__addEvent2Q <- function(obj_, event) {
    invisible(.Call('_RcppQueues_HumanEventQ__addEvent2Q', PACKAGE = 'RcppQueues', obj_, event))
}

HumanEventQ__get_eventQ <- function(obj_) {
    .Call('_RcppQueues_HumanEventQ__get_eventQ', PACKAGE = 'RcppQueues', obj_)
}

#' Test method for \code{\link{testClass}}
#'
#' Multiplies two matrix together and returns result; should be equivalent to \code{testClass$testMethod()}
#' @export
testMethodCpp <- function(testClassEnv) {
    .Call('_RcppQueues_testMethodCpp', PACKAGE = 'RcppQueues', testClassEnv)
}

#' Test method for \code{\link{testClass}}
#'
#' grabs the public environment and prints out one of its values
#' @export
testPublicCpp <- function(publicEnv) {
    invisible(.Call('_RcppQueues_testPublicCpp', PACKAGE = 'RcppQueues', publicEnv))
}

#' @export
testSearchPath <- function(env) {
    invisible(.Call('_RcppQueues_testSearchPath', PACKAGE = 'RcppQueues', env))
}

